name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Verify package-lock is up to date
        run: |
          npm install --package-lock-only
          git diff --exit-code package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run all checks
        run: npm run check

  mandoline-eval:
    name: Mandoline Evaluation
    runs-on: ubuntu-latest
    needs: test
    if: success()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Mandoline evaluation
        env:
          MANDOLINE_API_KEY: ${{ secrets.MANDOLINE_API_KEY }}
        run: npx mandoline-ci run --verbose

  deployment-ready:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: All checks passed
        run: echo "All CI checks passed. Ready for deployment."